//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPI03.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Endereco = new HashSet<Endereco>();
            this.Pedido = new HashSet<Pedido>();
        }

        [Key]
        public int idCliente { get; set; }

        [Required]
        [DisplayName("Nome completo")]
        [MaxLength(150, ErrorMessage = "Quantidade maxima de 150 caracteres")]
        [MinLength(10, ErrorMessage = "Quantidade minima de 10 caracteres")]
        public string nomeCompletoCliente { get; set; }

        [Required]
        [DisplayName("E-mail")]
        [DataType(DataType.EmailAddress)]
        [Remote("VerificarEmail", "Account")]
        [MaxLength(100, ErrorMessage = "Quantidade maxima de 100 caracteres")]
        [MinLength(10, ErrorMessage = "Quantidade minima de 10 caracteres")]
        public string emailCliente { get; set; }

        [Required]
        [DisplayName("Senha")]
        [DataType(DataType.Password)]
        [MaxLength(15, ErrorMessage = "Quantidade maxima de 15 caracteres")]
        [MinLength(4, ErrorMessage = "Quantidade minima de 4 caracteres")]
        public string senhaCliente { get; set; }

        [Required]
        [Remote("isCPFValido", "Account")]
        [DisplayName("CPF: ")]
        [DataType(DataType.Password)]
        [StringLength(11)]
        public string CPFCliente { get; set; }


        [DisplayName("Celular")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Quantidade maxima de 15 caracteres")]
        public string celularCliente { get; set; }

        [DisplayName("Tel. Comercial")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Quantidade maxima de 15 caracteres")]
        public string telComercialCliente { get; set; }

        [DisplayName("Tel. Residencial")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Quantidade maxima de 15 caracteres")]
        public string telResidencialCliente { get; set; }

        [Required]
        [DisplayName("Data de nascimento")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{yyyy-MM-dd}")]
        public Nullable<System.DateTime> dtNascCliente { get; set; }
        public Nullable<bool> recebeNewsLetter { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endereco> Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
