//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPI03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
        }
    
        public int idProduto { get; set; }
        public string nomeProduto { get; set; }
        public string descProduto { get; set; }
        public decimal precProduto { get; set; }
        public Nullable<decimal> descontoPromocao { get; set; }
        public int idCategoria { get; set; }
        public string ativoProduto { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> qtdMinEstoque { get; set; }
        public byte[] imagem { get; set; }
        public string imagem64 { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
